### ISSUE TITLE
Can we implement Pod for slices?

### ISSUE THREAD

**Issue by icefoxen** [Lokathor/bytemuck#11]
Basically, is it possible to `impl Pod for &[T] where T: Pod`?  IIRC, slices must not include padding, so this SEEMS okay, and it would be nice to be able to turn `&[u64]` into `&[u8]`.

**Comment by Lokathor** [comment]
Slices are not `Pod`. They _can contain_ `Pod` data elements, in other words the pointer and length can indicate a `Pod` region of memory, but they are not themselves `Pod`, because the reference and length must follow all sorts of rules.

Have you tried the [cast_slice](https://docs.rs/bytemuck/1.1.0/bytemuck/fn.cast_slice.html) function?

**Comment by icefoxen** [comment]
Derp, `cast_slice` is what I want.  Thank you.
