### ISSUE TITLE
Comparison with other crates

### ISSUE THREAD

**Issue by philipc** [Lokathor/bytemuck#13]
There are a number of crates similar to this one:
- https://crates.io/crates/zerocopy
- https://crates.io/crates/plain
- https://crates.io/crates/zero
- https://crates.io/crates/pod

Did you evaluate any of these before deciding to write this crate, and if so can you give me your thoughts on why they weren't suitable? I need something like this crate and I'm interesting in learning if this crate solves any problems that the others don't.

**Comment by Lokathor** [comment]
With the prefix that I really hate doing comparisons between crates and I would generally like users to evaluate for themselves if a crate matches their needs...

## Crates I Didn't Know About Until Today When You Asked

* `pod` uses trait methods and there's a billion of them and it's complicated and I don't like that _even if_ it covered all my needs. I just hate that style of design so much that I'm not going to look closely to see if it does similar things or not. It's good for Iterator (since you've already called one method generally, either .iter() or .iter_mut(), perhaps .chars() or .bytes(), etc) and approximately nowhere else.
* `zero` is all about reading bytes off of an input stream and supports exactly 8 types, which makes it far too limited for most of what I want to do.
* `plain` seems to be _closer_ to what I'd make myself, except that it has an unsafe `Plain` trait and then doesn't even use it as bounds on the unsafe functions it provides, which could make them safe. Why would you do that? What? What we're doing with all these casts isn't complicated on the backend, so the only value that you're giving the user is that you've thought about it and you're making it safe for them so that they don't have to think about it.

## Crates I Knew About Before

* `zerocopy` This is, again, for like the millionth time, worried about doing casts to and from byte slices. Why do so many designs for this sort of thing care about that? Like I used that in my PNG parsing code, and never ever before did I really care about turning `&[u8]` into `&T`. Clearly there's a market for this stuff, but really I think they're focusing a whole lot on one specific sub-case of the broader picture and forgetting about all the other useful casts.

## Summary

If they work for you, please use them or continue to use them.

**Comment by philipc** [comment]
> This is, again, for like the millionth time, worried about doing casts to and from byte slices. Why do so many designs for this sort of thing care about that? Like I used that in my PNG parsing code, and never ever before did I really care about turning &[u8] into &T. Clearly there's a market for this stuff, but really I think they're focusing a whole lot on one specific sub-case of the broader picture and forgetting about all the other useful casts.

Ok thanks, that explains your motivation. I'm the opposite: I've only ever needed to handle byte slices, not casts between other types. Maybe you should document this is as a feature (to me "piles of bytes" means byte slices).

**Comment by Lokathor** [comment]
Note that in 1.1 the `from_bytes` function will do the `&[u8]` to `&T` directly (and in 1.0 you could cast the slice and take the 0th element).
