### ISSUE TITLE
Derives for traits?

### ISSUE THREAD

**Issue by icefoxen** [Lokathor/bytemuck#4]
Basically I'm wondering if it would be useful to have derive macros for `Pod` and `Zeroable`.  They could be hidden behind a feature flag so as to not make things slower in the simple case (similar to `serde_derive`), but could also automatically check that the various constraints for these traits are upheld.

**Comment by Lokathor** [comment]
Such a derive would have to live in its own crate because of how proc-macros work.

If someone makes the proc-macro for it I'll link to their work, but I basically don't want to do it myself.

**Comment by rodrimati1992** [comment]
I am going to implement a derive macro for `Zeroable`.

**Comment by Lokathor** [comment]
I'm happy to advertise it in the readme/lib here.

Zeroable seems easier, Pod seems trickier.

**Comment by rodrimati1992** [comment]
I created the [zeroable](https://crates.io/crates/zeroable) crate that exposes a `Zeroable` derive macro.
The macro has some limitations [which are described in the docs](https://docs.rs/zeroable/0.2.0/zeroable/zeroable_docs/index.html#restrictions).

**Comment by thomcc** [comment]
I've been hacking on this, as I'd need it to use bytemuck reasonably at work.

I took a look at @rodrimati1992 Zeroable derive and I think some of the cases it allows could be unsound, especially if you include things like the attributes, especially `#[zero(not_zeroable())]` which AFAICT really should have `unsafe` in its name (as it's possible for users to use it in an unsound way).

A lot of effort was spent on it clearly, but I think too much work was spent on trying to make the derive usable for all cases. IMO for cases which aren't obviously correct, the solution has to be to force the user to manually implement `unsafe trait Zeroable`. Ditto Pod (and `Contiguous` in #12  if it is accepted)

**Comment by rodrimati1992** [comment]
@thomcc Aside from using the Zeroable derive macro with unions,is there anything unsound about it?
If you feel strongly enough about the soundness of union attributes,you should create an issue in [here](https://github.com/rodrimati1992/zeroable_crates/issues).
I didn't feel like the union attributes needed an unsafe prefix,since accessing union fields is already unsafe(you have to ensure that the field has a valid value for its type).

**Comment by icefoxen** [comment]
I would say that if I have a type `Foo` that I can derive `Zeroable` on, then if I can do `let x: Foo = mem::zero();` and get an `Foo` the `Zeroable` trait is not sound.

**Comment by rodrimati1992** [comment]
It's not possible to get UB in code using the Zeroable derive macro,with structs or enums.

With unions you can get UB in unsafe code,if you marked a field as being not-zeroable,and yet access it anyway afterwards.

**Comment by Lokathor** [comment]
like `union { a: usize, b: NomZeroUsize }`?

**Comment by rodrimati1992** [comment]
Like:
```rust
#[derive(Zeroable)]
union Dummy{
    a:usize,

    #[zero(nonzero)]
    b:NonZeroUsize,
}
let um=Dummy::zeroed();
unsafe{
    println!("{}",um.b); // whoops,this field is not zeroable
}
```
This is what I think thomcc was describing when talking about allowing unsound code.

**Comment by Lokathor** [comment]
I merged https://github.com/Lokathor/bytemuck/pull/30, which added this to the repo.

I've since published the [bytemuck_derive](https://crates.io/crates/bytemuck_derive) crate as an alpha release (technically `1.0.0-alpha.2`), and I want to give people a little time to make sure things are fully working before declaring it a real 1.0 release.

Currently you can should be able to use the crate on its own without `bytemuck` having a `derive` feature by doing the following in `Cargo.toml`:

```toml
[dependencies]
bytemuck_derive = "1.0.0-alpha.2"
```

And then in your code:
```rust
use bytemuck_derive::{Zeroable, Pod, TransparentWrapper};
```

---

@LPGhatguy in the PR you expressed interest in using this with your stuff, could you try things out and report back?

**Comment by LPGhatguy** [comment]
Will do! I should have some time tomorrow.

**Comment by LPGhatguy** [comment]
The derives seem pretty good and functional. They caught a couple oversights in my codebase, actually!

However, the error messages aren't great. If there's padding in the struct, you'll get an error message like this:

![Picture of bad error message](https://user-images.githubusercontent.com/654598/90988573-93e6bd80-e548-11ea-92e3-a023d2207d1e.png)

Is this something that's fixable? If now not, can it be something we can fix later?

**Comment by Lokathor** [comment]
hmm.

what's the struct definition?

and what sort of error message would you expect?

**Comment by LPGhatguy** [comment]
I lost the original struct, but here's one that gives an error message with different numbers:

```rust
#[repr(C)]
#[derive(Clone, Copy, Zeroable, Pod)]
struct Oopsie {
    pub first: u16,
    pub second: f32,
}
```

I would want the macro to tells me I have padding, and ideally where it is!

**Comment by Lokathor** [comment]
Ah, okay, so that's checked for here
<https://github.com/Lokathor/bytemuck/blob/main/derive/src/traits.rs#L209-L225>
and I can kinda tell how that's turning into the error message you see, but i'm not a proc-macro pro so I'm not sure how to make the error message better than it currently is.
